development:
  adapter: postgresql
  encoding: unicode
  database: planner01_dev
  pool: 5
  host: localhost
  username: postgres
  password: Akarnani1
  

production:
  adapter: postgresql
  encoding: unicode
  database: planner01_production
  pool: 5
  host: localhost
  username: postgres
  password: Akarnani1
  